default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  port: 5432
  pool: 5

development:
  <<: *default
  database: pay_app_development

test:
  <<: *default
  database: pay_app_test

production:
  <<: *default
  database: pay_app_production
  username: pay_app
  password: <%= ENV['PAY_APP_DATABASE_PASSWORD'] %>